# Generated by Django 4.2 on 2024-12-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_city_province_useraddress_address_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date and time')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city', verbose_name='City')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'ProvinceCity',
                'verbose_name_plural': 'ProvinceCities',
            },
        ),
    ]
