# Generated by Django 4.2 on 2025-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_address_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='province',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='province',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='provincecities',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='provincecities',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='usersimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='usersimage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='usersreview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='usersreview',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
    ]
