# Generated by Django 4.2 on 2025-03-23 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date and time')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('sent_text', models.TextField(verbose_name='Sent_text')),
                ('respond_text', models.TextField(verbose_name='Respond_text')),
                ('is_responded', models.BooleanField(default=False, verbose_name='Is_responded')),
                ('responder_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responder_user', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
