# Generated by Django 4.2 on 2025-04-01 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sender_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
