# Generated by Django 4.2 on 2025-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_sender_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated date and time'),
        ),
    ]
