# Generated by Django 4.2 on 2025-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_connection_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
    ]
