# Generated by Django 4.2 on 2024-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebasket',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Count'),
        ),
    ]
