# Generated by Django 4.2 on 2025-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
    ]
