# Generated by Django 4.2 on 2025-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_alter_category_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
        migrations.AlterField(
            model_name='purchasebasket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='purchasebasket',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date and time'),
        ),
    ]
